### PR TITLE
Return the analysis from the lint pass too.

### PR DESCRIPTION
**Pull request by rictic**
- [x] CHANGELOG.md has been updated

---
This change is [Reviewable](https://reviewable.io/reviews/polymer/polymer-linter/132)

### CODE REVIEW

**Comment by rictic** [comment]
This is mostly useful for makeParseLoader, when called from the cli or the ide

**Review by valdrinkoshi — COMMENTED** [review]
Not clear why is this needed for, my understanding is that we now add an `analysis` property to an array. Is this needed internally only (for the tests) or elsewhere too?

**Comment by rictic** [comment]
It's also useful in the CLI and IDE which call the same makeParseLoader function

**Review by valdrinkoshi — APPROVED** [review]
👍

**Pull request merged**
