### PR TITLE
Prepare for release of v0.1.2

### PR DESCRIPTION
**Pull request by rictic**
- [x] CHANGELOG.md has been updated

---
This change is [Reviewable](https://reviewable.io/reviews/polymer/polymer-linter/22)

### CODE REVIEW

**Review by justinfagnani — APPROVED** [review]

**Comment by usergenic** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 16 at r1](https://reviewable.io:443/reviews/polymer/polymer-linter/22#-Kd2KMkg82ufZcfrCKhM:-Kd2KMkg82ufZcfrCKhN:brm2prx) ([raw file](https://github.com/polymer/polymer-linter/blob/7960ae1530af5a949687d25225a88608f34f81c7/CHANGELOG.md#L16)):*
> ```Markdown
> - allRules and allRuleCollections on the registry, for accessing all registered rules and collections.
> 
> ## [0.1.1] - 2017-02-10
> ```

This is because 0.1.1 was the released version and this was previously incorrect on CHANGELOG?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/polymer/polymer-linter/22)*

**Comment by usergenic** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/polymer/polymer-linter/22#-:-Kd2KjJPg_IXAii5cVsR:bnfp4nl)*

**Comment by usergenic** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/polymer/polymer-linter/22)*

**Comment by rictic** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGELOG.md, line 16 at r1](https://reviewable.io:443/reviews/polymer/polymer-linter/22#-Kd2KMkg82ufZcfrCKhM:-Kd2KdjsZ0SsC9hoL0qF:blo96b3) ([raw file](https://github.com/polymer/polymer-linter/blob/7960ae1530af5a949687d25225a88608f34f81c7/CHANGELOG.md#L16)):*
<details><summary><i>Previously, usergenic (Brendan Baldwin) wrote…</i></summary><blockquote>

This is because 0.1.1 was the released version and this was previously incorrect on CHANGELOG?
</blockquote></details>

Yeah. I had 0.1.0 in package.json and did `np patch` and here we are.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/polymer/polymer-linter/22)*

**Pull request merged**
