### PR TITLE
Prepare to release v2.3.0

### PR DESCRIPTION
**Pull request by rictic**
- [x] CHANGELOG.md has been updated

---
This change is [Reviewable](https://reviewable.io/reviews/polymer/polymer-linter/137)

### CODE REVIEW

**Comment by bicknellr** [comment]
LGTM

**Review by bicknellr — APPROVED** [review]

**Review by bicknellr — CHANGES_REQUESTED** [review]
Does this need to update package.json?

**Review by bicknellr — APPROVED** [review]
(from other discussion) No, apparently this happens later.

**Comment by rictic** [comment]
Nah, we let `np` do that after we merge

**Pull request merged**
