### PR TITLE
Update to typescript v2.6

### PR DESCRIPTION
**Pull request by rictic**
- [x] CHANGELOG.md has been updated

Just unused code. This may not compile until the analyzer has been updated.

---
This change is [Reviewable](https://reviewable.io/reviews/polymer/polymer-linter/117)

### CODE REVIEW

**Review by valdrinkoshi — CHANGES_REQUESTED** [review]
could you also update `src/test/util.ts`? it currently errors with (18,11): error TS6133: '_printer' is declared but its value is never read.

**Comment by valdrinkoshi** [comment]
Also, `src/polymer/call-super-in-callbacks.ts` has issues with types in the `estraverse.traverse(` calls: Two different types with this name exist, but they are unrelated (?!)

**Comment by rictic** [comment]
The estraverse error is due to `npm link`. An upcoming version of typescript will do this smarter I think (hope)

**Comment by rictic** [comment]
Fixed the `_printer` error and updated to new analyzer.

**Review by valdrinkoshi — APPROVED** [review]

**Pull request merged**
